import Foundation

struct Country {
    var name: String
    var flag: String
    var code: String
}

let countries = [
    Country(name: "Россия", flag: "🇷🇺", code: "+7"),
    Country(name: "США", flag: "🇺🇸", code: "+1"),
    Country(name: "Казахстан", flag: "🇰🇿", code: "+1999"),
    Country(name: "Канада", flag: "🇨🇦", code: "+1"),
    Country(name: "Австралия", flag: "🇦🇺", code: "+61"),
    Country(name: "Германия", flag: "🇩🇪", code: "+49"),
    Country(name: "Франция", flag: "🇫🇷", code: "+33"),
    Country(name: "Великобритания", flag: "🇬🇧", code: "+44"),
    Country(name: "Италия", flag: "🇮🇹", code: "+39"),
    Country(name: "Испания", flag: "🇪🇸", code: "+34"),
    Country(name: "Мексика", flag: "🇲🇽", code: "+52"),
    Country(name: "Бразилия", flag: "🇧🇷", code: "+55"),
    Country(name: "Аргентина", flag: "🇦🇷", code: "+54"),
    Country(name: "Япония", flag: "🇯🇵", code: "+81"),
    Country(name: "Южная Корея", flag: "🇰🇷", code: "+82"),
    Country(name: "Китай", flag: "🇨🇳", code: "+86"),
    Country(name: "Индия", flag: "🇮🇳", code: "+91"),
    Country(name: "Индонезия", flag: "🇮🇩", code: "+62"),
    Country(name: "Турция", flag: "🇹🇷", code: "+90"),
    Country(name: "Египет", flag: "🇪🇬", code: "+20"),
    Country(name: "Южноафриканская Республика", flag: "🇿🇦", code: "+27"),
    Country(name: "Новая Зеландия", flag: "🇳🇿", code: "+64"),
    Country(name: "Филиппины", flag: "🇵🇭", code: "+63"),
    Country(name: "Вьетнам", flag: "🇻🇳", code: "+84"),
    Country(name: "Пакистан", flag: "🇵🇰", code: "+92"),
    Country(name: "Бангладеш", flag: "🇧🇩", code: "+880"),
    Country(name: "Нигерия", flag: "🇳🇬", code: "+234"),
    Country(name: "Кения", flag: "🇰🇪", code: "+254"),
    Country(name: "Саудовская Аравия", flag: "🇸🇦", code: "+966"),
    Country(name: "ОАЭ", flag: "🇦🇪", code: "+971"),
    Country(name: "Иран", flag: "🇮🇷", code: "+98"),
    Country(name: "Ирак", flag: "🇮🇶", code: "+964"),
    Country(name: "Австрия", flag: "🇦🇹", code: "+43"),
    Country(name: "Швейцария", flag: "🇨🇭", code: "+41"),
    Country(name: "Швеция", flag: "🇸🇪", code: "+46"),
    Country(name: "Норвегия", flag: "🇳🇴", code: "+47"),
    Country(name: "Дания", flag: "🇩🇰", code: "+45"),
    Country(name: "Нидерланды", flag: "🇳🇱", code: "+31"),
    Country(name: "Бельгия", flag: "🇧🇪", code: "+32"),
    Country(name: "Польша", flag: "🇵🇱", code: "+48"),
    Country(name: "Чехия", flag: "🇨🇿", code: "+420"),
    Country(name: "Румыния", flag: "🇷🇴", code: "+40"),
    Country(name: "Греция", flag: "🇬🇷", code: "+30"),
    Country(name: "Португалия", flag: "🇵🇹", code: "+351"),
    Country(name: "Болгария", flag: "🇧🇬", code: "+359"),
    Country(name: "Хорватия", flag: "🇭🇷", code: "+385"),
    Country(name: "Словения", flag: "🇸🇮", code: "+386"),
    Country(name: "Латвия", flag: "🇱🇻", code: "+371"),
    Country(name: "Литва", flag: "🇱🇹", code: "+370"),
    Country(name: "Эстония", flag: "🇪🇪", code: "+372"),
    Country(name: "Ирландия", flag: "🇮🇪", code: "+353"),
    Country(name: "Финляндия", flag: "🇫🇮", code: "+358"),
    Country(name: "Мальта", flag: "🇲🇹", code: "+356"),
    Country(name: "Черногория", flag: "🇲🇪", code: "+382"),
    Country(name: "Сербия", flag: "🇷🇸", code: "+381"),
    Country(name: "Македония", flag: "🇲🇰", code: "+389"),
    Country(name: "Косово", flag: "🇽🇰", code: "+383"),
    Country(name: "Словения", flag: "🇸🇮", code: "+386"),
    Country(name: "Албания", flag: "🇦🇱", code: "+355"),
    Country(name: "Люксембург", flag: "🇱🇺", code: "+352"),
    Country(name: "Кипр", flag: "🇨🇾", code: "+357"),
    Country(name: "Армения", flag: "🇦🇲", code: "+374"),
    Country(name: "Азербайджан", flag: "🇦🇿", code: "+994"),
    Country(name: "Грузия", flag: "🇬🇪", code: "+995"),
    Country(name: "Молдова", flag: "🇲🇩", code: "+373"),
    Country(name: "Беларусь", flag: "🇧🇾", code: "+375"),
    Country(name: "Монголия", flag: "🇲🇳", code: "+976"),
    Country(name: "Таджикистан", flag: "🇹🇯", code: "+992"),
    Country(name: "Узбекистан", flag: "🇺🇿", code: "+998"),
    Country(name: "Кыргызстан", flag: "🇰🇬", code: "+996"),
    Country(name: "Туркмения", flag: "🇹🇲", code: "+993"),
    Country(name: "Фиджи", flag: "🇫🇯", code: "+679"),
    Country(name: "Тонга", flag: "🇹🇴", code: "+676"),
    Country(name: "Самоа", flag: "🇼🇸", code: "+685"),
    Country(name: "Сейшельские острова", flag: "🇸🇨", code: "+248"),
    Country(name: "Барбадос", flag: "🇧🇧", code: "+1246"),
    Country(name: "Сент-Люсия", flag: "🇱🇨", code: "+1758"),
    Country(name: "Гренада", flag: "🇬🇩", code: "+1473"),
    Country(name: "Ямайка", flag: "🇯🇲", code: "+1-876"),
    Country(name: "Гаити", flag: "🇭🇹", code: "+509"),
    Country(name: "Антигуа и Барбуда", flag: "🇦🇬", code: "+1268"),
    Country(name: "Гренада", flag: "🇬🇩", code: "+1473"),
    Country(name: "Маврикий", flag: "🇲🇺", code: "+230"),
    Country(name: "Сент-Китс и Невис", flag: "🇰🇳", code: "+1869"),
    Country(name: "Доминика", flag: "🇩🇲", code: "+1767"),
    Country(name: "Суринам", flag: "🇸🇷", code: "+597"),
    Country(name: "Тринидад и Тобаго", flag: "🇹🇹", code: "+1868"),
    Country(name: "Лаос", flag: "🇱🇦", code: "+856"),
    Country(name: "Шри-Ланка", flag: "🇱🇰", code: "+94"),
    Country(name: "Непал", flag: "🇳🇵", code: "+977"),
    Country(name: "Мальдивы", flag: "🇲🇻", code: "+960"),
    Country(name: "Маврикий", flag: "🇲🇺", code: "+230"),
    Country(name: "Бутан", flag: "🇧🇹", code: "+975"),
    Country(name: "Тимор-Лешти", flag: "🇹🇱", code: "+670")
]

